apiVersion: v1
kind: Service
metadata:
  name: game-sudoku
  namespace: game
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: game-sudoku
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-sudoku
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-sudoku
  template:
    metadata:
      labels:
        app: game-sudoku
    spec:
      containers:
        - name: backend
          image: dockergelb/sudoku
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: game
spec:
  ingressClassName: nginx
  rules:
    - host: sudoku.kholinar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-sudoku
                port:
                  number: 80