apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bridge4-sudoku
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/stmcallister/vcluster-bridge4-sudoku.git
    targetRevision: HEAD
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: game

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
